name: Keep Alive

on:
  schedule:
    - cron: "0 12 1 * *"  # ogni 1° del mese a mezzogiorno
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Keep workflows alive
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git commit --allow-empty -m "chore: keep workflows alive"
          git push
